import { faker } from '@faker-js/faker';
import { mockImgCover } from '../utils/mockImages';

const TITLE = [
  '大卒者の就職率、依然厳しく',
  '台風18号、南九州は今夜にも暴風域',
  '経常黒字、最高に',
  '平塚の七夕始まる',
  '工場野菜や乾燥野菜に人気',
  '女性が一生に生む子どもの数、最低に',
  '感動の千円',
  '関東地方など梅雨入り',
  'プロスポーツ、人気の一位は野球',
  '何でも持ち込める入試',
  'オフィス街で弁当ブーム',
  '障害者向けソフト',
  '外国人や若者にも盆栽ブーム',
  'アルコール自販機にカードを導入',
  '疲れている中学生',
  '愛する人との食事',
  '箱いっぱいのキス',
  'そばかすよりかっこいいのは？',
  '技術の価値',
  '不思議な木',
  'バブルラップ',
  'お金より自信',
  '木の器',
  'フォークはそのままで',
  '体で一番大切な所',
  'バンドエイドの誕生',
  '科学と美術の交差点',
  'フリオの2度目の情熱',
  '父がしたかったこと',
  'AIBOの葬式',
  'まぼろしの国を求めて',
  '古代から続く「和の精神」',
  '永遠のライバル',
  '個性的な戦国大名',
  '技術者の誇り',
  '女性経営者の先駆け',
  '日本のファストフード',
  '情報革命',
  '成功する秘訣',
  '怪談の名人',
  'わびの精神',
  '妥協しない',
  '水玉の女王',
  'タングルウッドの奇跡',
  '瓢箪から駒'
];

const DESCRIPTION = [
  '卒業者、就職、最高、大学院',
  '台風、風速、勢力、暴風',
  '黒字、最高、貿易',
  '七夕祭り、有名、三大、竹飾り',
  '工場野菜、乾燥野菜、凍結、天候',
  '最低、人口、自然増加、件数',
  'JR、交番、老夫婦、多すぎる',
  '梅雨入り、早く',
  '野球、プロスポーツ、世論調査',
  '入試、試験場、能力',
  '弁当、ブーム、専門店、お袋の味',
  '障害者、コミュニケーション、キーの操作',
  '盆栽、ブーム、インテリア',
  'アルコール、自動販売機、購入',
  '中学生、疲れた、アンケート調査',
  '食事、老人ホーム、認知症',
  'クリスマス、箱、父親',
  'そばかす、動物園、かっこいい',
  'エンジン、技術、船、ハンマー',
  '木、パンク修理、枝',
  'バブルラップ、壁紙、飛行機',
  '失敗、老人、小切手、一所懸命、自信',
  'おじいさん、ため息をつく、食事、食器',
  '病気、遺言、牧師、聖書、ひつぎ',
  '体、大切、成長、質問',
  'バンドエイド、医療用、ガーゼ、完全滅菌',
  '科学、美術、偽物、交差点',
  'サッカー選手、交通事故、音楽、情熱',
  '本棚、道具、父、一緒に',
  '犬のロボット、ソニー、人の形のロボット',
  '古代史、謎、夢、情熱、好奇心',
  '伝説、和、集団主義、価値観、憲法',
  '女性作家の活躍、ライバル、仮名文字（国風文化）、小説・随筆',
  '南蛮文化（外国文化の影響）、伝統、個性、国家の統一',
  '技術者、創業者、経営、世襲',
  '女性経営者、ビジネス、女性の地位、ドラマ',
  '寿司、発明、食文化、ビジネスチャンス',
  '経営、情報革命、理念、未来予測',
  'アイドル、起業、信念、運',
  '落語、伝統芸能、ユーモア、娯楽',
  '茶道、伝統文化、わびの精神、文化の継承',
  '日本映画、完璧主義、時代劇',
  'ブランド品、前衛芸術、ビジネスと芸術（コラボレーション）',
  '天才ヴァイオリニスト、英才教育、親離れ、子育て、親子関係',
  '文豪、小説、エリート、本業と副業、神経衰弱'
];

const DOCUMENT_URL = [
  '/document/news/1. 大卒者の就職率、依然厳しく.pdf',
  '/document/news/2. 台風18号、南九州は今夜にも暴風域.pdf',
  '/document/news/3. 経常黒字、最高に.pdf',
  '/document/news/4. 平塚の七夕始まる.pdf',
  '/document/news/5. 工場野菜や乾燥野菜に人気.pdf',
  '/document/news/6. 女性が一生に生む子どもの数、最低に.pdf',
  '/document/news/7. 感動の千円.pdf',
  '/document/news/8. 関東地方など梅雨入り.pdf',
  '/document/news/9. プロスポーツ、人気の一位は野球.pdf',
  '/document/news/10. 何でも持ち込める入試.pdf',
  '/document/news/11.　オフィス街で弁当ブーム.pdf',
  '/document/news/12. 障害者向けソフト.pdf',
  '/document/news/13. 外国人や若者にも盆栽ブーム.pdf',
  '/document/news/14. アルコール自販機にカードを導入.pdf',
  '/document/news/15. 疲れている中学生.pdf',
  '/document/short_stories/1. 愛する人との食事.pdf',
  '/document/short_stories/2. 箱いっぱいのキス.pdf',
  '/document/short_stories/3. そばかすよりかっこいいのは？.pdf',
  '/document/short_stories/4. 技術の価値.pdf',
  '/document/short_stories/5. 不思議な木.pdf',
  '/document/short_stories/6. バブルラップ.pdf',
  '/document/short_stories/7. お金より自信.pdf',
  '/document/short_stories/8. 木の器.pdf',
  '/document/short_stories/9. フォークはそのままで.pdf',
  '/document/short_stories/10. 体で一番大切な所.pdf',
  '/document/short_stories/11. バンドエイドの誕生.pdf',
  '/document/short_stories/12. 科学と美術の交差点.pdf',
  '/document/short_stories/13. フリオの2度目の情熱.pdf',
  '/document/short_stories/14. 父がしたかったこと.pdf',
  '/document/short_stories/15. AIBOの葬式.pdf',
  '/document/the_greate_japanese/1. まぼろしの国を求めて.pdf',
  '/document/the_greate_japanese/2.　古代から続く「和の精神」.pdf',
  '/document/the_greate_japanese/3. 永遠のライバル.pdf',
  '/document/the_greate_japanese/4. 個性的な戦国大名.pdf',
  '/document/the_greate_japanese/5. 技術者の誇り.pdf',
  '/document/the_greate_japanese/6. 女性経営者の先駆け.pdf',
  '/document/the_greate_japanese/7. 日本のファストフード.pdf',
  '/document/the_greate_japanese/8. 情報革命.pdf',
  '/document/the_greate_japanese/9. 成功する秘訣.pdf',
  '/document/the_greate_japanese/10. 怪談の名人.pdf',
  '/document/the_greate_japanese/11. わびの精神.pdf',
  '/document/the_greate_japanese/12. 妥協しない.pdf',
  '/document/the_greate_japanese/13. 水玉の女王.pdf',
  '/document/the_greate_japanese/14. タングルウッドの奇跡.pdf',
  '/document/the_greate_japanese/15. 瓢箪から駒.pdf'
];

const TEST_URL = [
  'https://forms.gle/6ZXFCyQhX5cB4mNfA',
  'https://forms.gle/vCXVR3fEH8rNGUmq8',
  'https://forms.gle/hR5NPeLzSdH5uvuF8',
  'https://forms.gle/WFJa4k8mApzyTq8p7',
  'https://forms.gle/tAwmCCHMCmJBX8ELA',
  'https://forms.gle/3ZFaT4hYoin2AFGU9',
  'https://forms.gle/wvT2xuBf8gWSCvVMA',
  'https://forms.gle/BUTUMfjbGtkprsyb9',
  'https://forms.gle/C2WV36YMeuyUACap9',
  'https://forms.gle/HZuSNWLrzF6j3wJX6',
  'https://forms.gle/cpZzDvnZcQrVQoAn7',
  'https://forms.gle/dF6W3Dmx7aQReQy77',
  'https://forms.gle/PAYjps1eL52u53sK9',
  'https://forms.gle/9V3KJbMaic4zNd3w9',
  'https://forms.gle/74VGLjp2qHaMXrco7',
  'https://forms.gle/xpeFaRiffSLPN26z5',
  'https://forms.gle/d6G3UXxKd6ZMnHa17',
  'https://forms.gle/kDE8nTmL6LzMPt4B6',
  'https://forms.gle/bQ2qW1YLnzxuLpk88',
  'https://forms.gle/GHkSqY1S7chaQib66',
  'https://forms.gle/zrH8wEeAZs82mPnt7',
  'https://forms.gle/qFc8oxQfHF8babL99',
  'https://forms.gle/U54PPU167Co2gozc9',
  'https://forms.gle/rhxdXAotgDhEkDUv5',
  'https://forms.gle/DAJPBeJhL1urqBDEA',
  'https://forms.gle/CcAUBdy6FJc7WDN27',
  'https://forms.gle/QieHLyenYxipKA718',
  'https://forms.gle/NBpKK2Q1FWCiaxmv8',
  'https://forms.gle/xhKCR7ruNnfdLbQ1A',
  'https://forms.gle/Sp4FLozvwnZYsziU9',
  'https://forms.gle/m6LGdKm643HjME4K8',
  'https://forms.gle/ZFXJjB53UHN4Jsxs5',
  'https://forms.gle/t6zqgwv3n2cyLAKP6',
  'https://forms.gle/fSdyrUtFrhkiZavU8',
  'https://forms.gle/QsoWmueBtYVyVmZHA',
  'https://forms.gle/ET37Dmu5n2MTZHJc8 ',
  'https://forms.gle/MLk6CtGmRwAAUdEC9',
  'https://forms.gle/xmH71Wx9s8AjuZQUA',
  'https://forms.gle/CcQRcNXL71RnheoT6',
  'https://forms.gle/koSyj5pJhA23V33G9',
  'https://forms.gle/iRKHZuWU3by4wsPE9',
  'https://forms.gle/sWSBv2Z96G3DZGip6',
  'https://forms.gle/rz81iobes5qkvhmj6',
  'https://forms.gle/Ft9ThYEejMGZAjRF8',
  'https://forms.gle/AYurRySFbSaYd7c99'
];

const documents = [...Array(45)]
  .map((_, index) => {
    let docType = 1;
    if (index < 15) docType = 1;
    if (index >= 15 && index < 30) docType = 2;
    if (index >= 30 && index < 45) docType = 3;
    return {
      cover: mockImgCover(index + 1),
      id: index + 1,
      type: docType,
      state: 1,
      title: TITLE[index],
      description: DESCRIPTION[index],
      documentUrl: DOCUMENT_URL[index],
      testUrl: TEST_URL[index],
      createdAt: faker.date.past(),
      rating: faker.datatype.number({ min: 1, max: 5, precision: 0.1 }),
      view: faker.datatype.number({ min: 0, max: 20 })
    };
  })
  .sort((doc1, doc2) => doc2.createdAt - doc1.createdAt);

export default documents;
